import {expandPrehistoricRecords} from './prehistoric-dossiers.js';
const adw=slug=>({title:'Animal Diversity Web · University of Michigan',url:`https://animaldiversity.org/accounts/${slug}/`,accessedAt:'2026-09-24'});
const nhm=slug=>({title:'Natural History Museum, London',url:`https://www.nhm.ac.uk/discover/${slug}`,accessedAt:'2026-09-24'});
const animal=(name,scientificName,family,diet,range,habitat,anatomy,source,note='Loài tham chiếu cho bản demo; tên asset không xác nhận phân loài.')=>({name,scientificName,category:'animals',entityType:'organism',taxonomy:['Animalia','Chordata','Mammalia',family],summary:anatomy,identityNote:note,attributes:[{key:'diet',label:'Thức ăn',type:'text',value:diet,sourceIds:[0]},{key:'range',label:'Phân bố',type:'text',value:range,sourceIds:[0]},{key:'habitat',label:'Môi trường sống',type:'text',value:habitat,sourceIds:[0]},{key:'locomotion',label:'Vận động',type:'text',value:'Di chuyển trên bốn chân',sourceIds:[0]}],sources:[source]});
const ancient=(name,scientificName,group,period,range,diet,anatomy,source,note)=>({name,scientificName,category:'dinosaurs',entityType:'organism',taxonomy:['Animalia','Chordata',group],summary:anatomy,identityNote:note||'Model minh họa phục dựng; màu da và chuyển động không phải bằng chứng hóa thạch.',attributes:[{key:'period',label:'Niên đại',type:'text',value:period,sourceIds:[0]},{key:'range',label:'Nơi tìm thấy hóa thạch',type:'text',value:range,sourceIds:[0]},{key:'diet',label:'Thức ăn',type:'text',value:diet,sourceIds:[0]},{key:'extinct',label:'Tình trạng',type:'boolean',value:true,display:'Đã tuyệt chủng',sourceIds:[0]}],sources:[source]});
export const SPECIES={
 trex:ancient('Tyrannosaurus rex','Tyrannosaurus rex','Dinosauria · Theropoda','Phấn Trắng muộn, khoảng 68–66 triệu năm trước','Bắc Mỹ','Ăn thịt','Đi bằng hai chân, đầu lớn, hàm khỏe và chi trước ngắn. Đuôi góp phần cân bằng cơ thể.',nhm('dino-directory/tyrannosaurus.html')),
 stego:ancient('Stegosaurus','Stegosaurus','Dinosauria · Stegosauria','Jura muộn','Bắc Mỹ','Ăn thực vật','Có các tấm xương lớn dọc lưng và gai ở đuôi. Di chuyển bằng bốn chân.',nhm('dino-directory/stegosaurus.html')),
 trice:ancient('Triceratops','Triceratops','Dinosauria · Ceratopsia','Phấn Trắng muộn','Bắc Mỹ','Ăn thực vật','Hộp sọ có diềm xương và ba sừng; mỏ giúp cắt thực vật. Cơ thể được nâng đỡ bằng bốn chân.',nhm('dino-directory/triceratops.html')),
 deino:ancient('Deinonychus','Deinonychus antirrhopus','Dinosauria · Dromaeosauridae','Phấn Trắng sớm','Bắc Mỹ','Ăn thịt','Khủng long hai chân với móng lớn cong ở ngón chân thứ hai và đuôi dài. Model này chưa thể hiện bộ lông phục dựng.',nhm('dino-directory/deinonychus.html')),
 ptero:ancient('Pterosaur','Pterosauria · chưa xác định loài','Pterosauria','Đại Trung sinh','Nhiều khu vực trên thế giới','Thay đổi theo loài; một số loài ăn cá','Bò sát bay có màng cánh được nâng đỡ bởi ngón tay thứ tư kéo dài.',nhm('the-truth-about-pterosaurs.html'),'Pterosaur là bò sát bay, không thuộc Dinosauria. Tên Pteradactal của file không đủ xác định loài; hồ sơ này mô tả nhóm Pterosauria.'),
 mosa:ancient('Mosasaurus','Mosasaurus','Squamata · Mosasauridae','Phấn Trắng muộn','Trầm tích biển ở nhiều khu vực','Ăn động vật biển','Bò sát biển có các chi biến đổi thành vây và đuôi hỗ trợ bơi.',nhm('what-is-a-mosasaur.html'),'Mosasaurus là bò sát biển, không phải khủng long. Hồ sơ ở cấp chi; chưa xác định loài của asset.'),
 wolf:animal('Sói xám','Canis lupus','Canidae','Chủ yếu động vật có vú','Bắc Mỹ và lục địa Á–Âu','Rừng, lãnh nguyên, đồng cỏ và vùng khô hạn','Có lớp lông dày, mõm dài và chân thích nghi với việc di chuyển trên cạn. Sống thành các nhóm xã hội.',adw('Canis_lupus')),
 fox:animal('Cáo đỏ','Vulpes vulpes','Canidae','Động vật nhỏ, côn trùng và quả','Phân bố rộng ở Bắc bán cầu; được du nhập vào một số nơi khác','Rừng, đồng cỏ và cảnh quan gần khu dân cư','Tai nhọn, mõm thon và đuôi nhiều lông; thích nghi với nhiều môi trường sống.',adw('Vulpes_vulpes')),
 bear:animal('Gấu · mẫu tham chiếu','Ursus arctos','Ursidae','Ăn tạp: thực vật, côn trùng và động vật','Bắc Mỹ và lục địa Á–Âu','Rừng và vùng núi, cùng một số môi trường mở','Thân lớn, chi khỏe và bàn chân tiếp đất bằng cả lòng bàn chân. Thành phần thức ăn thay đổi theo vùng.',adw('Ursus_arctos'),'Asset chỉ ghi Bear; chưa xác minh là gấu nâu hay gấu đen. Thông tin dưới đây dùng gấu nâu Ursus arctos làm hồ sơ tham chiếu, không xác nhận định danh model.'),
 boar:animal('Lợn rừng','Sus scrofa','Suidae','Ăn tạp: rễ, củ, quả và động vật nhỏ','Bản địa Á–Âu và Bắc Phi; du nhập ở nhiều nơi','Rừng, đồng cỏ và các sinh cảnh có nước','Mõm khỏe dùng đào bới, lông cứng và răng nanh phát triển. Đi bằng các ngón có móng guốc.',adw('Sus_scrofa')),
 hyena:animal('Linh cẩu đốm','Crocuta crocuta','Hyaenidae','Săn mồi và ăn xác động vật','Châu Phi hạ Sahara','Đồng cỏ, savanna và một số vùng núi','Vai cao hơn phần hông, hàm khỏe và lông có đốm. Sống trong những nhóm xã hội phức tạp.',adw('Crocuta_crocuta')),
 lion:animal('Sư tử cái','Panthera leo','Felidae','Chủ yếu thú móng guốc','Châu Phi và một quần thể tại Ấn Độ','Savanna, đồng cỏ và rừng thưa','Sư tử cái thường không có bờm; thân cơ bắp, móng có thể thu lại. Con cái trong đàn thường hợp tác săn mồi.',adw('Panthera_leo'),'Model Lioness biểu diễn cá thể cái; hồ sơ ở cấp loài Panthera leo, không xác định phân loài.'),
};
expandPrehistoricRecords(SPECIES);
export const ANIMAL_IDS=['wolf','fox','bear','boar','hyena','lion'];
