import {createEntranceCamera} from './entrance-camera.js';
import {defaultPlaybackSpeed} from './playback-defaults.js';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {createTrexModel} from './model.js';
import {createHuntActions} from './hunt.js';
import {createTrexActions,ACTIONS} from './actions.js';
import {createPterosaurModel} from './pterosaur.js';
import {createImportedCreature} from './imported-creature.js';
import {createModelGallery} from './model-gallery.js';
import {createAnimalCreature} from './animal-rig.js';
import {SPECIES,ANIMAL_IDS} from './species-data.js';
import {createSpeciesPanel} from './species-panel.js';
const $=id=>document.getElementById(id);
async function boot(){
 document.querySelector('aside .eyebrow').textContent='CHUYỂN ĐỘNG GỐC & TỰ TẠO';
 document.querySelector('aside .note').textContent='7 clip gốc và 3 động tác tự tạo bằng rig. Nhảy và đánh hơi tự trở về quan sát; ngã chết lặp lại khi kết thúc. Chọn động tác khác để đứng lại. Chưa có con mồi tương tác.';
 let animalAssets;async function getAnimals(){if(!animalAssets){const bytes=Uint8Array.from(atob($('animal-data').textContent.trim()),c=>c.charCodeAt(0));animalAssets=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).json();}return animalAssets;}
 const raw=Uint8Array.from(atob($('model-data').textContent.trim()),c=>c.charCodeAt(0));const stream=new Blob([raw]).stream().pipeThrough(new DecompressionStream('gzip'));const data=await new Response(stream).json();
 let model=await createTrexModel({data,...JSON.parse($('textures').textContent)}),runtime=model.userData.sculptRuntime,definitions={...ACTIONS,hunt:[null,'S\u0103n \u0111u\u1ed5i','T-Rex \u0111u\u1ed5i v\u00e0 b\u1eaft Deino. B\u1ea5m ph\u00e1t l\u1ea1i \u0111\u1ec3 xem l\u1ea1i c\u1ea3nh.',false]},modelId='trex';const cache={trex:{model,definitions}};
 const host=$('stage'),renderer=new T.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;host.prepend(renderer.domElement);
 const scene=new T.Scene();scene.add(model);scene.add(new T.HemisphereLight(0xe9f5de,0x6e7459,2.2));const sun=new T.DirectionalLight(0xffedce,3);sun.position.set(6,10,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-9,right:9,top:9,bottom:-9,near:.1,far:35});sun.shadow.bias=-.0002;sun.shadow.normalBias=.015;scene.add(sun);const rim=new T.DirectionalLight(0xc7e5ff,1.5);rim.position.set(-5,5,-6);scene.add(rim);
 const floor=new T.Mesh(new T.CylinderGeometry(6.3,6.3,.12,96),new T.MeshStandardMaterial({color:0xc3cbb7,roughness:1}));floor.position.y=-.08;floor.receiveShadow=true;scene.add(floor);
 const ring=new T.Mesh(new T.RingGeometry(5.7,5.72,100),new T.MeshBasicMaterial({color:0x9caa8e,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=-.012;scene.add(ring);
 const camera=new T.PerspectiveCamera(37,1,.05,100),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=2;controls.maxDistance=32;controls.maxPolarAngle=Math.PI*.49;
 const preyBytes=$('deino-data')?Uint8Array.from(atob($('deino-data').textContent.trim()),c=>c.charCodeAt(0)):null;
 const huntPrey=preyBytes?(await createImportedCreature(preyBytes,'deino')).model:null;if(!huntPrey)delete definitions.hunt;
 function makeActions(root,defs){const base=createTrexActions(root,root.name==='trex'?ACTIONS:defs);const speed=defaultPlaybackSpeed(modelId);base.setSpeed(speed);$('speed').value=speed;$('speed-value').textContent=speed+'×';return root.name==='trex'&&huntPrey?createHuntActions({base,predator:root,prey:huntPrey,scene,camera,controls,floor,ring}):base;}
 let actions=makeActions(model,definitions),skeleton=new T.SkeletonHelper(runtime.source);skeleton.visible=false;skeleton.material.depthTest=false;skeleton.renderOrder=10;scene.add(skeleton);
 const entrance=createEntranceCamera(camera,controls,host);
 const views={hero:[10,5,12],side:[14,3,0],head:[5,3,8]};let view='hero';function setView(id){view=id;entrance.cancel();if(id==='hero'&&!actions.hunt?.active){entrance.frame(model,modelId);return;}if(actions.hunt?.active){actions.frameView(id);return;}controls.target.set(0,1.15,0);camera.position.set(...views[id]);if(id==='head'){model.updateMatrixWorld(true);runtime.sockets.head.getWorldPosition(controls.target);camera.position.copy(controls.target).add(new T.Vector3(3,1.2,3.4));}else{if(host.clientWidth<600)camera.position.multiplyScalar(1.12);if(runtime.sockets.head.userData.viewCenter){const center=new T.Vector3().fromArray(runtime.sockets.head.userData.viewCenter);if(modelId==='ptero'&&['pteranodonSit','pteranodonRoar'].includes(actions.state.id))center.y=1.15;camera.position.y+=center.y-controls.target.y;controls.target.y=center.y;}}controls.update();}
 function resize(){renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();if(view==='hero'&&!actions.hunt?.active&&!entrance.active)entrance.frame(model,modelId,{animate:false});}new ResizeObserver(resize).observe(host);resize();setView('hero');
 function populate(){ $('actions').innerHTML=Object.keys(definitions).map((id,i)=>`<button class="action" data-action="${id}">${definitions[id][1]}</button>`).join('');document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{actions.play(b.dataset.action);sync();}); }populate();
 let pteroGrounded=false; function sync(){const grounded=modelId==='ptero'&&['pteranodonSit','pteranodonRoar'].includes(actions.state.id);if(grounded!==pteroGrounded){pteroGrounded=grounded;const y=grounded?1.15:(runtime.sockets.head.userData.viewCenter?.[1]??1.15);camera.position.y+=y-controls.target.y;controls.target.y=y;controls.update();}const names={stego:'Stegosaurus',mosa:'Mosasaurus',trice:'Triceratops',deino:'Deinonychus'};if(names[modelId]){document.querySelector('.title h1').textContent=names[modelId];document.querySelector('.title p').textContent=modelId==='deino'?'Rig tự tạo · 7 chuyển động':'Toàn bộ animation gốc';}document.querySelector('aside .note').textContent=modelId==='trex'?'Nhảy: co–duỗi chân, giữ chân khi lấy đà và tiếp đất, quỹ đạo trọng lực. Ngã dùng clip toàn thân gốc, lặp lại khi kết thúc; chưa phải ragdoll.':'Bay gốc và chao cánh lượn bổ sung: nghiêng thân, điều chỉnh cánh và đường lượn nhẹ.';if(names[modelId])document.querySelector('aside .note').textContent=modelId==='deino'?'Rig thử nghiệm: quan sát, đi rình tại chỗ, bật nhảy.':'Giữ nguyên toàn bộ clip animation, rig và vật liệu gốc. Texture tối đa 1024 px.';document.querySelectorAll('[data-action]').forEach(b=>{b.classList.toggle('active',b.dataset.action===actions.state.id);b.setAttribute('aria-pressed',String(b.dataset.action===actions.state.id));});$('action-title').textContent=modelId==='trex'?definitions[actions.state.id][1]:String(Object.keys(definitions).indexOf(actions.state.id)+1);$('action-note').textContent=modelId==='trex'?definitions[actions.state.id][2]:'';document.querySelector('aside .note').hidden=modelId!=='trex';$('pause').textContent=actions.state.paused?'▶ Tiếp tục':'Ⅱ Tạm dừng';const record=SPECIES[modelId];if(record){document.querySelector('.title h1').textContent=record.name;document.querySelector('.title p').textContent=record.scientificName;document.querySelector('.title small').textContent=record.category==='animals'?'ĐỘNG VẬT':'SINH VẬT TIỀN SỬ';}document.querySelector('aside .note').hidden=true;}
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{actions.play(b.dataset.action);sync();});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('pause').onclick=()=>{actions.pause();sync();};$('replay').onclick=()=>{actions.play(actions.state.id);sync();};$('speed').oninput=e=>{actions.setSpeed(e.target.value);$('speed-value').textContent=Number(e.target.value).toFixed(2).replace(/0$/,'')+'×';};$('skeleton').onchange=e=>skeleton.visible=e.target.checked;$('normal').onchange=e=>{for(const m of Object.values(runtime.meshes)){for(const mat of Array.isArray(m.material)?m.material:[m.material])if(mat.normalScale)mat.normalScale.setScalar(e.target.checked?.65:0);}};
 function zoom(f){camera.position.sub(controls.target).multiplyScalar(f).clampLength(2,32).add(controls.target);controls.update();}$('zoom-in').onclick=()=>zoom(.85);$('zoom-out').onclick=()=>zoom(1.18);
 $('stats').textContent=`${runtime.stats.triangles.toLocaleString('vi-VN')} tam giác · ${Object.keys(definitions).length} chuyển động`;$('loading').hidden=true;sync();let last=performance.now(),lastId=actions.state.id;
 function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(document.hidden)return;actions.update(dt);if(actions.hunt?.active)entrance.cancel();entrance.update(dt);controls.update();if(lastId!==actions.state.id){lastId=actions.state.id;sync();}$('progress').style.width=(actions.progress*100)+'%';renderer.render(scene,camera);}requestAnimationFrame(frame);
 if($('pterosaur-data')){
  const chooser=document.createElement('select');chooser.id='model-select';chooser.setAttribute('aria-label','Chọn model');chooser.innerHTML='<option value="trex">T-Rex · Khủng long bạo chúa</option><option value="ptero">Pterosaur · Bò sát bay</option>';for(const [id,name] of [['stego','Stegosaurus'],['mosa','Mosasaurus'],['trice','Triceratops'],['deino','Deinonychus · Rig tự tạo']]){if($(id+'-data'))chooser.add(new Option(name,id),id==='stego'?1:id==='trice'?2:undefined);}if($('animal-data'))for(const id of ANIMAL_IDS)chooser.add(new Option(SPECIES[id].name,id));document.querySelector('aside').prepend(chooser);
  chooser.onchange=async()=>{const next=chooser.value;chooser.disabled=true;$('loading').hidden=false;$('loading').textContent='Đang đổi model…';try{
   if(!cache[next]&&ANIMAL_IDS.includes(next)){const a=await getAnimals();cache[next]=await createAnimalCreature(a.models[next],a.textures,next);}
   if(!cache[next]){const bytes=Uint8Array.from(atob($(next==='ptero'?'pterosaur-data':next+'-data').textContent.trim()),c=>c.charCodeAt(0));cache[next]=next==='ptero'?await createPterosaurModel(bytes):await createImportedCreature(bytes,next);}
   actions.dispose();scene.remove(model,skeleton);skeleton.geometry.dispose();skeleton.material.dispose();({model,definitions}=cache[next]);runtime=model.userData.sculptRuntime;modelId=next;scene.add(model);actions=makeActions(model,definitions);skeleton=new T.SkeletonHelper(runtime.source);skeleton.visible=$('skeleton').checked;skeleton.material.depthTest=false;skeleton.renderOrder=10;scene.add(skeleton);$('normal').checked=true;for(const m of Object.values(runtime.meshes)){const mats=Array.isArray(m.material)?m.material:[m.material];for(const mat of mats)if(mat.normalScale)mat.normalScale.setScalar(next==='trex'?.65:1);}populate();sync();setView('hero');
   document.querySelector('.title h1').innerHTML=next==='trex'?'Tyrannosaurus<span>rex.</span>':'Pterosaur<span>flight.</span>';document.querySelector('.title p').textContent=next==='trex'?'Khủng long bạo chúa':'Bò sát bay · Animation gốc';document.querySelector('aside .note').textContent=next==='trex'?'Nhảy/ngã dùng trọng lực, phản lực nền và giảm chấn đơn giản, chưa phải ragdoll toàn thân. Các clip khác giữ nguyên.':'Giữ nguyên animation, màu, normal và vật liệu PBR nhúng trong GLB. Chưa thêm động tác tự tạo.';$('stats').textContent=runtime.stats.triangles.toLocaleString('vi-VN')+' tam giác · '+Object.keys(definitions).length+' chuyển động';
  }catch(e){console.error(e);chooser.value=modelId;$('loading').textContent='Không đổi được model: '+e.message;return;}finally{chooser.disabled=false;}sync();$('loading').hidden=true;};
 }
 if($('model-select'))createModelGallery($('model-select'));
 createSpeciesPanel({getId:()=>modelId,getActions:()=>actions});
 window.trexDemo={ready:true,get model(){return model;},get actions(){return actions;},get modelId(){return modelId;},renderer,camera,scene,controls,entrance};window.dinosaurDemo=window.trexDemo;
}
boot().catch(e=>{console.error(e);$('loading').textContent='Không mở được mô hình. Hãy thử Chrome hoặc Edge bản mới có bật WebGL. '+e.message;});
